# Generated by Django 5.2.8 on 2025-11-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('picture', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_title', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=24)),
                ('fax', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_title', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=24)),
                ('fax', models.CharField(max_length=24)),
                ('homepage', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('quantity_per_unit', models.CharField(max_length=20)),
                ('unit_price', models.FloatField()),
                ('units_in_stock', models.SmallIntegerField()),
                ('units_on_order', models.SmallIntegerField()),
                ('reorder_level', models.SmallIntegerField()),
                ('discontinued', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.categories')),
                ('supllier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.suppliers')),
            ],
        ),
    ]
